.TH RERVER 1 rerver\-0.x
.SH NAME
rerver \- rust fullstack (actix + yew) servers quick manager

.SH QUICK
.P
First time writing a manpage gonna finish this later

.SH SYNOPSIS
.B rerver
.RB [ \-h
.IR help ]
.P
.BR rerver " ..."

.SH DESCRIPTION
.B rerver
rust fullstack (actix + yew) servers quick manager

.SH AUTHOR
.B zilezia https://github.com/Zilezia
